= Contributing to SC Kill Monitor

First off, thanks for taking the time to contribute.

The following is a set of guidelines for contributing to SC Kill Monitor, which is https://gitlab.com/flightsimtools/sc/sc-kill-monitor[hosted with GitLab].
These are mostly guidelines, not rules.
Use your best judgment and feel free to propose changes to this document in a merge request.

== Table Of Contents

* <<code-of-conduct, Code of Conduct>>
* <<i-dont-want-to-read-this-whole-thing-ive-a-question, I don't want to read this whole thing. I've a question.>>
* <<how-can-i-contribute, How Can I Contribute?>>
* <<reporting-bugs, Reporting Bugs>>
* <<suggesting-enhancements, Suggesting Enhancements>>
* <<your-first-code-contribution, Your First Code Contribution>>
* <<merge-requests, Merge Requests>>
* <<style-guides, Style Guides>>
* <<git-commit-messages-style-guide, Git Commit Messages Style Guide>>
* <<java-style-guide, Java Style Guide>>
* <<javadoc-style-guide, JavaDoc Style Guide>>

[#code-of-conduct]
== Code of Conduct

This project and everyone who participates in it are governed by the link:CODE_OF_CONDUCT.adoc[Code of Conduct].
By participating, you're expected to uphold this code.
Report unacceptable behavior to link:mailto:lucas.greuloch@pm.me[lucas.greuloch@pm.me].

[#i-dont-want-to-read-this-whole-thing-ive-a-question]
== I don't want to read this whole thing. I've a question.

First, you can read the documentation or search the wiki for the information you need.

If you need help by the developers, create an issue with your question and add the label *support* to it.
*Perform a cursory search* to see if your question has already been asked.
If it has, add a comment to the existing issue instead of opening a new one.

____

*Note:* If you find a *Closed* issue that seems like it is the same topic that you're looking for, open a new issue and include a link to the original issue in the body of your new one.

____

[#how-can-i-contribute]
== How Can I Contribute?

[#reporting-bugs]
=== Reporting Bugs

This section guides you through submitting a bug report for SC Kill Monitor.
Following these guidelines helps maintainers and the community to understand your report, reproduce the behavior, and find related reports.

Before creating bug reports, check <<before-submitting-a-bug-report,this list>> as you might find out that  you don't need to create one.
When you're creating a bug report, <<how-do-i-submit-a-good-bug-report,include as many details as possible>>.
Fill out link:.gitlab/issue_templates/Bug.md[the required template], the information it asks for helps us to resolve issues faster.
You can  likewise submit a new (bug-)issue by sending it to link:mailto:contact-project+flightsimtools-sc-sc-kill-monitor-67138143-issue-@incoming.gitlab.com[contact-project+flightsimtools-sc-sc-kill-monitor-67138143-issue-@incoming.gitlab.com].

[#before-submitting-a-bug-report]
==== Before Submitting A Bug Report

* *Check the FAQ* for a list of common questions and problems.
* *Perform a cursory search* to see if the problem has already been reported.
If it has, *and the issue is still open*, add a comment to the existing issue instead of opening a new one.

____

*Note:* If you find a *Closed* issue that seems like it is the same thing that you're experiencing, open a new issue and include a link to the original issue in the body of your new one.

____

[#how-do-i-submit-a-good-bug-report]
==== How Do I Submit A (Good) Bug Report?

Bugs are tracked as Issues. Provide the following information by filling in link:.gitlab/issue_templates/Bug.md[the template].

Explain the problem and include additional details to help maintainers reproduce the problem:

* *Use a clear and descriptive title* for the issue to identify the problem.
* *Describe the exact steps which reproduce the problem* in as many details as possible.
For example, start by explaining how you started the software. When listing steps, *don't only say what you did, but explain how you did it*.
* *Provide specific examples to demonstrate the steps.*
Include links to files, other projects or copy/pasteable snippets, which you use in those examples.
If you're providing snippets in the issue, use https://gitlab.com/help/user/markdown#code-and-syntax-highlighting[Markdown code blocks].
* *Describe the behavior you observed after following the steps* and point out what exactly is the problem with that behavior.
* *Explain which behavior you expected to see instead and why.*
* *Include screenshots and animated GIFs* which show you following the described steps and clearly demonstrate the problem.
* *If you're reporting that SC Kill Monitor crashed*, include a crash report with a stack trace from the operating system.
Include the crash report in the issue in https://gitlab.com/help/user/markdown#code-and-syntax-highlighting[code block], a file attachment, or put it in a https://gitlab.com/dashboard/snippets[snippet] and provide the link to that snippet.
* *If the problem wasn't triggered by a specific action*, describe what you were doing before the problem happened and share more information using the guidelines below.

Provide more context by answering these questions:

* *Did the problem start happening recently,* or was this always a problem?
* If the problem started happening recently, *can you reproduce the problem in an older version of SC Kill Monitor?*
What is the most recent version in which the problem doesn't happen?
You can download older versions of SC Kill Monitor from the release's directory.
* *Can you reliably reproduce the issue?*
If not, provide details about how often the problem happens and under which conditions it normally happens.
* If the problem is related to working with files (for example, opening and editing files), *does the problem happen for all files and projects or only some?* Is there anything else special about the files you're using?

Include details about your configuration and environment:

* *Which version of SC Kill Monitor are you using?*
* *What is the name and version of the OS you're using*?
* *What is your Java version and type* (JRE or JDK)**?**
* *What is your Java distribution* (for example Oracle, OpenJDK, Eclipse Temurin, Amazon Coretto, IBM, Azul Zulu, …)**?**
* *Are you running SC Kill Monitor in a virtual machine or a container?*
If so, which VM/Container software are you using and which operating systems and versions are used for the host and the guest?

[#suggesting-enhancements]
=== Suggesting Enhancements

This section guides you through submitting an enhancement suggestion for SC Kill Monitor, including completely new features and minor improvements to existing functionality.
Following these guidelines helps maintainers and the community to understand your suggestion and find related suggestions.

Before creating enhancement suggestions, check <<before-submitting-an-enhancement-suggestion,this list>> as you might find out that you don't need to create one.
When you're creating an enhancement suggestion, <<how-do-i-submit-a-good-enhancement-suggestion,include as many details as possible>>.
Fill in link:.gitlab/issue_templates/Feature.md[the template], including the steps that you imagine you would take if the feature you're requesting existed.
You can likewise submit a new (feature-)issue by sending it to link:mailto:contact-project+flightsimtools-sc-sc-kill-monitor-67138143-issue-@incoming.gitlab.com[contact-project+flightsimtools-sc-sc-kill-monitor-67138143-issue-@incoming.gitlab.com].

[#before-submitting-an-enhancement-suggestion]
==== Before Submitting An Enhancement Suggestion

* *Perform a cursory search* to see if the enhancement has already been suggested.
If it has, add a comment to the existing issue instead of opening a new one.

____

*Note:* If you find a *Closed* issue that seems like it is the same thing that you're suggesting, and you've new arguments to implement it, open a new issue and include a link to the original issue in the body of your new one.

____

[#how-do-i-submit-a-good-enhancement-suggestion]
==== How Do I Submit A (Good) Enhancement Suggestion?

Enhancement suggestions are tracked as Issues. Create an issue and provide the following information:

* *Use a clear and descriptive title* for the issue to identify the suggestion.
* *Provide a step-by-step description of the suggested enhancement* in as many details as possible.
* *Provide specific examples to demonstrate the steps*.
Include copy/pasteable snippets which you use in those examples, as https://gitlab.com/help/user/markdown#code-and-syntax-highlighting[Markdown code blocks].
* *Describe the current behavior* and *explain which behavior you expected to see instead* and why.
* *Include screenshots and animated GIFs* which help you demonstrate the steps or point out the part which the suggestion is related to.
* *Explain why this enhancement would be useful* to most SC Kill Monitor users.
* *Specify which version of SC Kill Monitor you're using.*
//* *Specify the name and version of the browser you're using.*
* *Specify the name and version of the Java distribution you're using* (for example Oracle, OpenJDK, Eclipse Temurin, Amazon Coretto, IBM, Azul Zulu, …).
* *Specify the name and version of the OS you're using.*

[#your-first-code-contribution]
=== Your First Code Contribution

Unsure where to begin contributing to SC Kill Monitor? You can start by looking through these `beginner` and `help-wanted` issues:

* *Beginner issues* – issues which should only require a few lines of code, and a test or two.
* *Help wanted issues* – issues which should be a bit more involved than `beginner` issues.

[#merge-requests]
=== Merge Requests

* Open a merge request (MR) against the _develop_ branch.
* Prefix the MR name with one of the following types: "FEATURE", "BUG", "CHORE", "META" and the affected part of the software.
For example, [FEATURE – Database] or [BUG – API].
* Fill in link:.gitlab/merge_request_templates/Merge_Request.md[the required template].
* Don't include issue numbers in the title.
* Include screenshots or animated GIFs in your merge request whenever possible.
* Document new code based on the <<style-guides,Style Guides>>.
* End all files with a newline.
* Avoid platform-dependent code.

[#style-guides]
== Style Guides

[#git-commit-messages-style-guide]
=== Git Commit Messages Style Guide

* Use the present tense ("Add feature" not "Added feature")
* Use the imperative mood ("Move cursor to…" not "Moves cursor to…")
* Limit the first line to 72 characters or fewer
* Reference issues and merge requests (`relates to #XYZ` or `relates to !XYZ`)
* Add `[skip ci]` to the commit message to skip the ci pipeline if it doesn't need to run

[#java-style-guide]
=== Java Style Guide

* Follow the https://google.github.io/styleguide/javaguide.html[Java Style Guide] of Google.
You can find the XML file for IntelliJ IDEA in the settings directory.
* Use two spaces for idents.

[#javadoc-style-guide]
=== JavaDoc Style Guide

* Always update the `@author` tag, but don't delete the old authors.
* Use the `@since` tag